// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PumpLogix
{
    public partial class CardValidatorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CardValidatorTest))]
public void TestValidCardNumber407()
{
    this.TestValidCardNumber(new string('0', 15));
}
[TestMethod]
[PexGeneratedBy(typeof(CardValidatorTest))]
public void TestValidCardNumber501()
{
    this.TestValidCardNumber("228484127254698");
}
[TestMethod]
[PexGeneratedBy(typeof(CardValidatorTest))]
public void TestValidCardNumber207()
{
    this.TestValidCardNumber("000000000005090");
}
[TestMethod]
[PexGeneratedBy(typeof(CardValidatorTest))]
[ExpectedException(typeof(ArgumentException))]
public void TestValidCardNumberThrowsArgumentException826()
{
    this.TestValidCardNumber(new string('0', 17));
}
    }
}
